namespace UnmaxedBot.Modules.Runescape.Api.HighscoreLite.Model
{
    public enum HighscoreSkillType
    {
        Overall,
        Attack,
        Defense,
        Strength,
        Consitution,
        Ranged,
        Prayer,
        Magic,
        Cooking,
        Woodcutting,
        Fletching,
        Fishing,
        Firemaking,
        Crafting,
        Smithing,
        Mining,
        Herblore,
        Agility,
        Thieving,
        Slayer,
        Farming,
        Runecrafting,
        Hunter,
        Construction,
        Summoning,
        Dungeoneering,
        Divination,
        Invention
    }
}
